import { Share, Linking } from 'react-native';
import { Country, MealPlan } from '@/types';

type GroceryItem = {
  name: string;
  amount: number;
  unit: string;
};

/**
 * Aggregate ingredients from multiple recipes into a combined grocery list.
 */
export function aggregateGroceries(
  plans: MealPlan[],
  countries: Country[],
): GroceryItem[] {
  const map = new Map<string, GroceryItem>();

  for (const plan of plans) {
    const c = countries.find(cn => cn.id === plan.countryId);
    if (!c) continue;
    const recipe = plan.recipeId.endsWith('-dessert') ? c.dessert : c.mainDish;
    if (!recipe) continue;

    for (const ing of recipe.ingredients) {
      const name = typeof ing.name === 'string' ? ing.name : ing.name.en;
      const unit = typeof ing.unit === 'string' ? ing.unit : ing.unit.en;
      const key = `${name.toLowerCase()}|${unit.toLowerCase()}`;
      const existing = map.get(key);
      if (existing) {
        existing.amount += ing.amount;
      } else {
        map.set(key, { name, amount: ing.amount, unit });
      }
    }
  }

  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Export grocery list as a formatted text via native share.
 */
export async function shareGroceryList(items: GroceryItem[]): Promise<void> {
  if (items.length === 0) return;

  let text = 'Grocery List\n\n';
  for (const item of items) {
    text += `- ${item.amount.toFixed(1)} ${item.unit} ${item.name}\n`;
  }
  text += '\nGenerated by World Food Explorer';

  await Share.share({
    message: text,
    title: 'Grocery List',
  });
}

/**
 * Generate CSV content from grocery list.
 */
export function toCSV(items: GroceryItem[]): string {
  let csv = 'Item,Amount,Unit\n';
  for (const item of items) {
    const name = item.name.includes(',') ? `"${item.name}"` : item.name;
    csv += `${name},${item.amount.toFixed(1)},${item.unit}\n`;
  }
  return csv;
}

/**
 * Try to open Instacart with a search query (deep link).
 * Falls back to web URL if app not installed.
 */
export async function openInstacart(items: GroceryItem[]): Promise<void> {
  const query = items.slice(0, 10).map(i => i.name).join(', ');
  const webUrl = `https://www.instacart.com/store/search/${encodeURIComponent(query)}`;

  try {
    const canOpen = await Linking.canOpenURL(webUrl);
    if (canOpen) {
      await Linking.openURL(webUrl);
    }
  } catch {
    // Silently fail
  }
}

/**
 * Try to open Amazon Fresh with a search query.
 */
export async function openAmazonFresh(items: GroceryItem[]): Promise<void> {
  const query = items.slice(0, 5).map(i => i.name).join(' ');
  const url = `https://www.amazon.com/s?k=${encodeURIComponent(query)}&i=amazonfresh`;

  try {
    await Linking.openURL(url);
  } catch {
    // Silently fail
  }
}
