import type { StringTable } from './index';

export type CookbookStrings = {
  tabTitle: string;
  title: string;
  subtitle: string;
  savedSection: string;
  cookedSection: string;
  savedEmptyHint: string;
  cookedEmptyHint: string;
  emptyTitle: string;
  emptyBody: string;
  emptyCta: string;
  /** Cooking time, e.g. "45 min". */
  minutes: string;
  mainDish: string;
  dessert: string;
  locked: string;
  removed: string;
  undo: string;
  removeA11y: string;
  ratingA11y: string;
};

export const cookbookStrings: StringTable<CookbookStrings> = {
  en: {
    tabTitle: 'Cookbook',
    title: 'My Cookbook',
    subtitle: 'Dishes from around the world that you’ve saved and cooked',
    savedSection: 'Saved recipes',
    cookedSection: 'Cooked dishes',
    savedEmptyHint: 'Tap the heart on any recipe to save it here.',
    cookedEmptyHint: 'Dishes you mark as cooked will appear here.',
    emptyTitle: 'Your cookbook is empty',
    emptyBody: 'Save the recipes you love and mark dishes as cooked — they’ll all be collected here.',
    emptyCta: 'Explore countries',
    minutes: '{count} min',
    mainDish: 'Main dish',
    dessert: 'Dessert',
    locked: 'Locked',
    removed: 'Removed from saved recipes',
    undo: 'Undo',
    removeA11y: 'Remove {dish} from saved recipes',
    ratingA11y: 'Your rating: {rating} out of 5',
  },
  sv: {
    tabTitle: 'Kokbok',
    title: 'Min kokbok',
    subtitle: 'Rätter från hela världen som du har sparat och lagat',
    savedSection: 'Sparade recept',
    cookedSection: 'Lagade rätter',
    savedEmptyHint: 'Tryck på hjärtat på ett recept för att spara det här.',
    cookedEmptyHint: 'Rätter du markerar som lagade visas här.',
    emptyTitle: 'Din kokbok är tom',
    emptyBody: 'Spara recepten du gillar och markera rätter som lagade – här samlas allt.',
    emptyCta: 'Utforska länder',
    minutes: '{count} min',
    mainDish: 'Huvudrätt',
    dessert: 'Efterrätt',
    locked: 'Låst',
    removed: 'Borttaget från sparade recept',
    undo: 'Ångra',
    removeA11y: 'Ta bort {dish} från sparade recept',
    ratingA11y: 'Ditt betyg: {rating} av 5',
  },
  de: {
    tabTitle: 'Kochbuch',
    title: 'Mein Kochbuch',
    subtitle: 'Deine gespeicherten und gekochten Gerichte aus aller Welt',
    savedSection: 'Gespeicherte Rezepte',
    cookedSection: 'Bereits gekocht',
    savedEmptyHint: 'Tippe bei einem Rezept auf das Herz, um es hier zu speichern.',
    cookedEmptyHint: 'Gerichte, die du als gekocht markierst, erscheinen hier.',
    emptyTitle: 'Dein Kochbuch ist noch leer',
    emptyBody: 'Speichere Rezepte, die dir gefallen, und markiere Gerichte als gekocht – hier findest du alles wieder.',
    emptyCta: 'Länder entdecken',
    minutes: '{count} Min.',
    mainDish: 'Hauptgericht',
    dessert: 'Dessert',
    locked: 'Gesperrt',
    removed: 'Aus gespeicherten Rezepten entfernt',
    undo: 'Rückgängig',
    removeA11y: '{dish} aus gespeicherten Rezepten entfernen',
    ratingA11y: 'Deine Bewertung: {rating} von 5',
  },
  fr: {
    tabTitle: 'Recettes',
    title: 'Mes recettes',
    subtitle: 'Les plats du monde entier que vous avez enregistrés et cuisinés',
    savedSection: 'Recettes enregistrées',
    cookedSection: 'Déjà cuisinés',
    savedEmptyHint: 'Touchez le cœur d’une recette pour l’enregistrer ici.',
    cookedEmptyHint: 'Les plats que vous marquez comme cuisinés apparaîtront ici.',
    emptyTitle: 'Aucune recette pour l’instant',
    emptyBody: 'Enregistrez les recettes qui vous plaisent et marquez les plats cuisinés : tout sera réuni ici.',
    emptyCta: 'Explorer les pays',
    minutes: '{count} min',
    mainDish: 'Plat principal',
    dessert: 'Dessert',
    locked: 'Verrouillé',
    removed: 'Retirée des recettes enregistrées',
    undo: 'Annuler',
    removeA11y: 'Retirer {dish} des recettes enregistrées',
    ratingA11y: 'Votre note : {rating} sur 5',
  },
  es: {
    tabTitle: 'Recetario',
    title: 'Mi recetario',
    subtitle: 'Los platos de todo el mundo que has guardado y cocinado',
    savedSection: 'Recetas guardadas',
    cookedSection: 'Ya cocinados',
    savedEmptyHint: 'Toca el corazón de cualquier receta para guardarla aquí.',
    cookedEmptyHint: 'Los platos que marques como cocinados aparecerán aquí.',
    emptyTitle: 'Tu recetario está vacío',
    emptyBody: 'Guarda las recetas que te gusten y marca los platos que cocines: aquí lo tendrás todo.',
    emptyCta: 'Explorar países',
    minutes: '{count} min',
    mainDish: 'Plato principal',
    dessert: 'Postre',
    locked: 'Bloqueado',
    removed: 'Eliminada de recetas guardadas',
    undo: 'Deshacer',
    removeA11y: 'Quitar {dish} de recetas guardadas',
    ratingA11y: 'Tu valoración: {rating} de 5',
  },
  it: {
    tabTitle: 'Ricettario',
    title: 'Il mio ricettario',
    subtitle: 'I piatti di tutto il mondo che hai salvato e cucinato',
    savedSection: 'Ricette salvate',
    cookedSection: 'Già cucinati',
    savedEmptyHint: 'Tocca il cuore di una ricetta per salvarla qui.',
    cookedEmptyHint: 'I piatti che segni come cucinati appariranno qui.',
    emptyTitle: 'Il tuo ricettario è vuoto',
    emptyBody: 'Salva le ricette che ami e segna i piatti che cucini: li ritroverai tutti qui.',
    emptyCta: 'Esplora i paesi',
    minutes: '{count} min',
    mainDish: 'Piatto principale',
    dessert: 'Dolce',
    locked: 'Bloccato',
    removed: 'Rimossa dalle ricette salvate',
    undo: 'Annulla',
    removeA11y: 'Rimuovi {dish} dalle ricette salvate',
    ratingA11y: 'Il tuo voto: {rating} su 5',
  },
  pl: {
    tabTitle: 'Przepisy',
    title: 'Moje przepisy',
    subtitle: 'Zapisane i ugotowane dania z całego świata',
    savedSection: 'Zapisane przepisy',
    cookedSection: 'Ugotowane dania',
    savedEmptyHint: 'Stuknij serce przy przepisie, aby go tu zapisać.',
    cookedEmptyHint: 'Tu pojawią się dania oznaczone jako ugotowane.',
    emptyTitle: 'Nie masz jeszcze przepisów',
    emptyBody: 'Zapisuj ulubione przepisy i oznaczaj ugotowane dania – wszystko znajdziesz tutaj.',
    emptyCta: 'Odkrywaj kraje',
    minutes: '{count} min',
    mainDish: 'Danie główne',
    dessert: 'Deser',
    locked: 'Zablokowane',
    removed: 'Usunięto z zapisanych przepisów',
    undo: 'Cofnij',
    removeA11y: 'Usuń {dish} z zapisanych przepisów',
    ratingA11y: 'Twoja ocena: {rating} na 5',
  },
  nl: {
    tabTitle: 'Kookboek',
    title: 'Mijn kookboek',
    subtitle: 'Gerechten van over de hele wereld die je hebt bewaard en gekookt',
    savedSection: 'Bewaarde recepten',
    cookedSection: 'Al gekookt',
    savedEmptyHint: 'Tik op het hartje bij een recept om het hier te bewaren.',
    cookedEmptyHint: 'Gerechten die je als gekookt markeert, verschijnen hier.',
    emptyTitle: 'Je kookboek is nog leeg',
    emptyBody: 'Bewaar recepten die je lekker vindt en markeer gerechten als gekookt – hier vind je ze allemaal terug.',
    emptyCta: 'Ontdek landen',
    minutes: '{count} min',
    mainDish: 'Hoofdgerecht',
    dessert: 'Dessert',
    locked: 'Vergrendeld',
    removed: 'Verwijderd uit bewaarde recepten',
    undo: 'Ongedaan maken',
    removeA11y: '{dish} verwijderen uit bewaarde recepten',
    ratingA11y: 'Jouw beoordeling: {rating} van 5',
  },
  pt: {
    tabTitle: 'Receitas',
    title: 'As minhas receitas',
    subtitle: 'Pratos de todo o mundo que guardou e cozinhou',
    savedSection: 'Receitas guardadas',
    cookedSection: 'Já cozinhados',
    savedEmptyHint: 'Toque no coração de qualquer receita para a guardar aqui.',
    cookedEmptyHint: 'Os pratos que marcar como cozinhados aparecerão aqui.',
    emptyTitle: 'Ainda não tem receitas',
    emptyBody: 'Guarde as receitas de que gosta e marque os pratos que cozinhou — ficam todos aqui.',
    emptyCta: 'Explorar países',
    minutes: '{count} min',
    mainDish: 'Prato principal',
    dessert: 'Sobremesa',
    locked: 'Bloqueado',
    removed: 'Removida das receitas guardadas',
    undo: 'Anular',
    removeA11y: 'Remover {dish} das receitas guardadas',
    ratingA11y: 'A sua avaliação: {rating} em 5',
  },
};

/** Extra copy for the shopping list screen and its entry point in the Plan tab. */
type ShoppingStrings = {
  openList: string;
  /** Badge count for accessibility, e.g. "3 to buy". */
  toBuyCount: string;
  addWeek: string;
  shareWeek: string;
  madeWith: string;
  noMatches: string;
  clearSearch: string;
  removeItem: string;
};

export const shoppingStrings: StringTable<ShoppingStrings> = {
  en: {
    openList: 'Open shopping list',
    toBuyCount: '{count} to buy',
    addWeek: 'Add this week’s ingredients to the shopping list',
    shareWeek: 'Share this week’s meal plan',
    madeWith: 'Made with World Food Journey',
    noMatches: 'No items match “{query}”',
    clearSearch: 'Clear search',
    removeItem: 'Remove {item}',
  },
  sv: {
    openList: 'Öppna inköpslistan',
    toBuyCount: '{count} att handla',
    addWeek: 'Lägg till veckans ingredienser i inköpslistan',
    shareWeek: 'Dela veckans måltidsplan',
    madeWith: 'Skapad med World Food Journey',
    noMatches: 'Inga varor matchar ”{query}”',
    clearSearch: 'Rensa sökning',
    removeItem: 'Ta bort {item}',
  },
  de: {
    openList: 'Einkaufsliste öffnen',
    toBuyCount: '{count} zu kaufen',
    addWeek: 'Zutaten dieser Woche zur Einkaufsliste hinzufügen',
    shareWeek: 'Essensplan dieser Woche teilen',
    madeWith: 'Erstellt mit World Food Journey',
    noMatches: 'Keine Einträge für „{query}“',
    clearSearch: 'Suche löschen',
    removeItem: '{item} entfernen',
  },
  fr: {
    openList: 'Ouvrir la liste de courses',
    toBuyCount: '{count} à acheter',
    addWeek: 'Ajouter les ingrédients de la semaine à la liste de courses',
    shareWeek: 'Partager le menu de la semaine',
    madeWith: 'Créé avec World Food Journey',
    noMatches: 'Aucun article ne correspond à « {query} »',
    clearSearch: 'Effacer la recherche',
    removeItem: 'Retirer {item}',
  },
  es: {
    openList: 'Abrir la lista de la compra',
    toBuyCount: '{count} por comprar',
    addWeek: 'Añadir los ingredientes de la semana a la lista de la compra',
    shareWeek: 'Compartir el menú de la semana',
    madeWith: 'Creado con World Food Journey',
    noMatches: 'Ningún artículo coincide con «{query}»',
    clearSearch: 'Borrar búsqueda',
    removeItem: 'Quitar {item}',
  },
  it: {
    openList: 'Apri la lista della spesa',
    toBuyCount: '{count} da comprare',
    addWeek: 'Aggiungi gli ingredienti della settimana alla lista della spesa',
    shareWeek: 'Condividi il menù della settimana',
    madeWith: 'Creato con World Food Journey',
    noMatches: 'Nessun articolo corrisponde a «{query}»',
    clearSearch: 'Cancella ricerca',
    removeItem: 'Rimuovi {item}',
  },
  pl: {
    openList: 'Otwórz listę zakupów',
    toBuyCount: 'Do kupienia: {count}',
    addWeek: 'Dodaj składniki z tego tygodnia do listy zakupów',
    shareWeek: 'Udostępnij jadłospis na ten tydzień',
    madeWith: 'Utworzono w World Food Journey',
    noMatches: 'Brak pozycji pasujących do „{query}”',
    clearSearch: 'Wyczyść wyszukiwanie',
    removeItem: 'Usuń {item}',
  },
  nl: {
    openList: 'Boodschappenlijst openen',
    toBuyCount: '{count} te kopen',
    addWeek: 'Ingrediënten van deze week aan de boodschappenlijst toevoegen',
    shareWeek: 'Weekmenu delen',
    madeWith: 'Gemaakt met World Food Journey',
    noMatches: 'Geen items gevonden voor ‘{query}’',
    clearSearch: 'Zoekopdracht wissen',
    removeItem: '{item} verwijderen',
  },
  pt: {
    openList: 'Abrir a lista de compras',
    toBuyCount: '{count} por comprar',
    addWeek: 'Adicionar os ingredientes da semana à lista de compras',
    shareWeek: 'Partilhar o plano de refeições da semana',
    madeWith: 'Criado com World Food Journey',
    noMatches: 'Nenhum artigo corresponde a «{query}»',
    clearSearch: 'Limpar pesquisa',
    removeItem: 'Remover {item}',
  },
};
