import { Share, Linking } from 'react-native';
import { Country, MealPlan, Recipe } from '@/types';
import { translateContent } from '@/lib/translate-content';

export type GroceryItem = {
  name: string;
  amount: number;
  unit: string;
};

/**
 * The recipe a meal plan entry refers to: the dessert for dessert slots,
 * otherwise the main dish. (Recipe ids don't reliably end in "-dessert",
 * e.g. "indonesia-klepon".)
 */
export function getPlannedRecipe(country: Country, plan: MealPlan): Recipe | undefined {
  if (country.dessert && (plan.mealType === 'dessert' || plan.recipeId === country.dessert.id)) {
    return country.dessert;
  }
  return country.mainDish;
}

/**
 * Aggregate ingredients from multiple recipes into a combined grocery list.
 * Items are merged on their English name/unit and returned in `language`.
 */
export function aggregateGroceries(
  plans: MealPlan[],
  countries: Country[],
  language = 'en',
): GroceryItem[] {
  const map = new Map<string, GroceryItem>();

  for (const plan of plans) {
    const c = countries.find(cn => cn.id === plan.countryId);
    if (!c) continue;
    const recipe = getPlannedRecipe(c, plan);
    if (!recipe) continue;

    for (const ing of recipe.ingredients) {
      const key = `${translateContent(ing.name, 'en').toLowerCase()}|${translateContent(ing.unit, 'en').toLowerCase()}`;
      const existing = map.get(key);
      if (existing) {
        existing.amount += ing.amount;
      } else {
        map.set(key, {
          name: translateContent(ing.name, language),
          amount: ing.amount,
          unit: translateContent(ing.unit, language),
        });
      }
    }
  }

  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name, language));
}

/**
 * Export grocery list as a formatted text via native share.
 */
export async function shareGroceryList(items: GroceryItem[]): Promise<void> {
  if (items.length === 0) return;

  let text = 'Grocery List\n\n';
  for (const item of items) {
    text += `- ${item.amount.toFixed(1)} ${item.unit} ${item.name}\n`;
  }
  text += '\nGenerated by World Food Journey';

  await Share.share({
    message: text,
    title: 'Grocery List',
  });
}

/**
 * Generate CSV content from grocery list.
 */
export function toCSV(items: GroceryItem[]): string {
  let csv = 'Item,Amount,Unit\n';
  for (const item of items) {
    const name = item.name.includes(',') ? `"${item.name}"` : item.name;
    csv += `${name},${item.amount.toFixed(1)},${item.unit}\n`;
  }
  return csv;
}

/**
 * Try to open Instacart with a search query (deep link).
 * Falls back to web URL if app not installed.
 */
export async function openInstacart(items: GroceryItem[]): Promise<void> {
  const query = items.slice(0, 10).map(i => i.name).join(', ');
  const webUrl = `https://www.instacart.com/store/search/${encodeURIComponent(query)}`;

  try {
    const canOpen = await Linking.canOpenURL(webUrl);
    if (canOpen) {
      await Linking.openURL(webUrl);
    }
  } catch {
    // Silently fail
  }
}

/**
 * Try to open Amazon Fresh with a search query.
 */
export async function openAmazonFresh(items: GroceryItem[]): Promise<void> {
  const query = items.slice(0, 5).map(i => i.name).join(' ');
  const url = `https://www.amazon.com/s?k=${encodeURIComponent(query)}&i=amazonfresh`;

  try {
    await Linking.openURL(url);
  } catch {
    // Silently fail
  }
}
